import{S as h,i as f}from"./assets/vendor-Bxdh33oY.js";(function(){const n=document.createElement("link").relList;if(n&&n.supports&&n.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))r(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const i of o.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&r(i)}).observe(document,{childList:!0,subtree:!0});function s(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function r(e){if(e.ep)return;e.ep=!0;const o=s(e);fetch(e.href,o)}})();const g="your_api_key_here",b="https://pixabay.com/api/";async function w(t,n=1,s=12){const r=`${b}?key=${g}&q=${encodeURIComponent(t)}&image_type=photo&orientation=horizontal&safesearch=true&page=${n}&per_page=${s}`;try{const e=await fetch(r);if(!e.ok)throw new Error("Failed to fetch images.");return await e.json()}catch(e){throw console.error("Error fetching images:",e),e}}let c;function L(t){const n=document.querySelector(".gallery"),s=t.map(r=>`
    <a class="gallery__item" href="${r.largeImageURL}">
      <img class="gallery__image" src="${r.webformatURL}" alt="${r.tags}" loading="lazy" />
      <div class="info">
        <p><b>Likes:</b> ${r.likes}</p>
        <p><b>Views:</b> ${r.views}</p>
        <p><b>Comments:</b> ${r.comments}</p>
        <p><b>Downloads:</b> ${r.downloads}</p>
      </div>
    </a>
  `).join("");n.insertAdjacentHTML("beforeend",s),c?c.refresh():c=new h(".gallery a",{captionsData:"alt",captionDelay:250})}function S(){const t=document.querySelector(".gallery");t.innerHTML=""}function y(t){f.error({title:"Error",message:t,position:"topRight"})}function $(t){f.info({title:"Info",message:t,position:"topRight"})}const q=document.querySelector(".search-form"),l=document.querySelector(".load-more"),p=document.querySelector(".loader");document.querySelector(".gallery");let u="",a=1;q.addEventListener("submit",async t=>{if(t.preventDefault(),u=t.currentTarget.elements.query.value.trim(),!u){y("Search query cannot be empty.");return}a=1,S(),m()});l.addEventListener("click",()=>{a+=1,m()});async function m(){try{_();const t=await w(u,a);if(d(),t.hits.length===0&&a===1){$("Sorry, there are no images matching your search query. Please try again!");return}L(t.hits),t.totalHits>a*t.hits.length?l.style.display="block":l.style.display="none"}catch{d(),y("Failed to load images. Please try again.")}}function _(){p.style.display="block"}function d(){p.style.display="none"}
//# sourceMappingURL=index.js.map
